# Generated by Django 3.2.8 on 2021-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_auto_20211006_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='repeats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='health',
            name='set',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
