# Generated by Django 3.2.8 on 2021-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_auto_20211006_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.PositiveIntegerField(default=1)),
                ('repeats', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excersie_1', models.CharField(blank=True, choices=[('아령들기', '아령들기'), ('스쿼트', '스쿼트'), ('없음', '없음')], max_length=100, null=True)),
                ('excersie_2', models.CharField(blank=True, choices=[('아령들기', '아령들기'), ('스쿼트', '스쿼트'), ('없음', '없음')], max_length=100, null=True)),
                ('excersie_3', models.CharField(blank=True, choices=[('아령들기', '아령들기'), ('스쿼트', '스쿼트'), ('없음', '없음')], max_length=100, null=True)),
            ],
        ),
    ]
