# Generated by Django 3.2.8 on 2021-10-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_healthcustom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcustom',
            old_name='repeats',
            new_name='repeats_1',
        ),
        migrations.AddField(
            model_name='healthcustom',
            name='repeats_2',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='healthcustom',
            name='repeats_3',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
