# Generated by Django 3.2.8 on 2021-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_auto_20211012_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcustom',
            name='excersie_1',
            field=models.CharField(choices=[('아령들기', '아령들기'), ('스쿼트', '스쿼트'), ('없음', '없음')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcustom',
            name='excersie_2',
            field=models.CharField(choices=[('아령들기', '아령들기'), ('스쿼트', '스쿼트'), ('없음', '없음')], max_length=100),
        ),
        migrations.AlterField(
            model_name='healthcustom',
            name='excersie_3',
            field=models.CharField(choices=[('아령들기', '아령들기'), ('스쿼트', '스쿼트'), ('없음', '없음')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
