# Generated by Django 3.2.8 on 2021-10-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0008_auto_20211012_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcustom',
            name='exercise_1',
            field=models.CharField(choices=[('Curl', '아령들기'), ('Squat', '스쿼트'), ('Push Up', '팔굽혀펴기'), ('없음', '없음')], max_length=100),
        ),
        migrations.AlterField(
            model_name='healthcustom',
            name='exercise_2',
            field=models.CharField(choices=[('Curl', '아령들기'), ('Squat', '스쿼트'), ('Push Up', '팔굽혀펴기'), ('없음', '없음')], max_length=100),
        ),
        migrations.AlterField(
            model_name='healthcustom',
            name='exercise_3',
            field=models.CharField(choices=[('Curl', '아령들기'), ('Squat', '스쿼트'), ('Push Up', '팔굽혀펴기'), ('없음', '없음')], max_length=100),
        ),
    ]
