# Generated by Django 3.2.8 on 2021-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_auto_20211012_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.AlterField(
            model_name='healthcustom',
            name='exercise_1',
            field=models.CharField(choices=[('Curl', '아령들기'), ('Squat', '스쿼트'), ('Push Up', '팔굽혀펴기'), ('End', '없음')], max_length=100),
        ),
        migrations.AlterField(
            model_name='healthcustom',
            name='exercise_2',
            field=models.CharField(choices=[('Curl', '아령들기'), ('Squat', '스쿼트'), ('Push Up', '팔굽혀펴기'), ('End', '없음')], max_length=100),
        ),
        migrations.AlterField(
            model_name='healthcustom',
            name='exercise_3',
            field=models.CharField(choices=[('Curl', '아령들기'), ('Squat', '스쿼트'), ('Push Up', '팔굽혀펴기'), ('End', '없음')], max_length=100),
        ),
    ]
